alias p3="python3"
alias cls="clear"
alias ls="ls --group-directories-first --color -F -h -x"
alias chrome="google-chrome-stable"
alias linecount="~/Github/code-line-counter/line_counter"
alias bg="python3 ~/Github/dotfiles/scripts/text-etching/tasklist.py"
