local Remap = require("xor.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>pb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<Leader>pf", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<Leader>pm", function()
    require("telescope.builtin").marks()
end)
nnoremap("<Leader>pr", function()
    require("telescope.builtin").registers()
end)
nnoremap("<Leader>rr", function()
    require("telescope.builtin").lsp_references()
end)
